CREATE TABLE users (
    id UUID PRIMARY KEY,
    name VARCHAR(255),
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    preference VARCHAR(255) DEFAULT NULL,
    weightUnit VARCHAR(255) DEFAULT NULL,
    heightUnit VARCHAR(255) DEFAULT NULL,

    weight INTEGER DEFAULT NULL,
    height INTEGER DEFAULT NULL, 
    imageUri VARCHAR(255) DEFAULT NULL, 
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);